type REQUEST_BOOKS = 'REQUEST_BOOKS';
const REQUEST_BOOKS: REQUEST_BOOKS = 'REQUEST_BOOKS';

type REQUEST_BOOKS_SUCCESS = 'REQUEST_BOOKS_SUCCESS';
const REQUEST_BOOKS_SUCCESS: REQUEST_BOOKS_SUCCESS = 'REQUEST_BOOKS_SUCCESS';

type REQUEST_BOOKS_FAIL = 'REQUEST_BOOKS_FAIL';
const REQUEST_BOOKS_FAIL: REQUEST_BOOKS_FAIL = 'REQUEST_BOOKS_FAIL';

export {
  REQUEST_BOOKS,
  REQUEST_BOOKS_SUCCESS,
  REQUEST_BOOKS_FAIL
}
