type REQUEST_PAGE = 'REQUEST_PAGE';
const REQUEST_PAGE: REQUEST_PAGE = 'REQUEST_PAGE';

type REQUEST_PAGE_SUCCESS = 'REQUEST_PAGE_SUCCESS';
const REQUEST_PAGE_SUCCESS: REQUEST_PAGE_SUCCESS = 'REQUEST_PAGE_SUCCESS';

type REQUEST_PAGE_FAIL = 'REQUEST_PAGE_FAIL';
const REQUEST_PAGE_FAIL: REQUEST_PAGE_FAIL = 'REQUEST_PAGE_FAIL';

type REQUEST_MODULE_BY_ID = 'REQUEST_MODULE_BY_ID';
const REQUEST_MODULE_BY_ID: REQUEST_MODULE_BY_ID = 'REQUEST_MODULE_BY_ID';

type REQUEST_MODULE_BY_ID_SUCCESS = 'REQUEST_MODULE_BY_ID_SUCCESS';
const REQUEST_MODULE_BY_ID_SUCCESS: REQUEST_MODULE_BY_ID_SUCCESS = 'REQUEST_MODULE_BY_ID_SUCCESS';

type REQUEST_MODULE_BY_ID_FAIL = 'REQUEST_MODULE_BY_ID_FAIL';
const REQUEST_MODULE_BY_ID_FAIL: REQUEST_MODULE_BY_ID_FAIL = 'REQUEST_MODULE_BY_ID_FAIL';

type CLEAR_MODULE_BY_ID = 'CLEAR_MODULE_BY_ID';
const CLEAR_MODULE_BY_ID: CLEAR_MODULE_BY_ID = 'CLEAR_MODULE_BY_ID';

export {
  REQUEST_PAGE,
  REQUEST_PAGE_SUCCESS,
  REQUEST_PAGE_FAIL,

  REQUEST_MODULE_BY_ID,
  REQUEST_MODULE_BY_ID_SUCCESS,
  REQUEST_MODULE_BY_ID_FAIL,
  CLEAR_MODULE_BY_ID
};
