type ADD_ERROR = 'ADD_ERROR';
const ADD_ERROR: ADD_ERROR = 'ADD_ERROR';

type REMOVE_ERROR = 'REMOVE_ERROR';
const REMOVE_ERROR: REMOVE_ERROR = 'REMOVE_ERROR';

export {
  ADD_ERROR,
  REMOVE_ERROR
};
