type REQUEST_DATA_1 = 'REQUEST_DATA_1';
const REQUEST_DATA_1: REQUEST_DATA_1 = 'REQUEST_DATA_1';
type REQUEST_DATA_1_SUCCESS = 'REQUEST_DATA_1_SUCCESS';
const REQUEST_DATA_1_SUCCESS: REQUEST_DATA_1_SUCCESS = 'REQUEST_DATA_1_SUCCESS';
type REQUEST_DATA_1_FAIL = 'REQUEST_DATA_1_FAIL';
const REQUEST_DATA_1_FAIL: REQUEST_DATA_1_FAIL = 'REQUEST_DATA_1_FAIL';

type REQUEST_DATA_2 = 'REQUEST_DATA_2';
const REQUEST_DATA_2: REQUEST_DATA_2 = 'REQUEST_DATA_2';
type REQUEST_DATA_2_SUCCESS = 'REQUEST_DATA_2_SUCCESS';
const REQUEST_DATA_2_SUCCESS: REQUEST_DATA_2_SUCCESS = 'REQUEST_DATA_2_SUCCESS';
type REQUEST_DATA_2_FAIL = 'REQUEST_DATA_2_FAIL';
const REQUEST_DATA_2_FAIL: REQUEST_DATA_2_FAIL = 'REQUEST_DATA_2_FAIL';

type REQUEST_ALL_DATA = 'REQUEST_ALL_DATA';
const REQUEST_ALL_DATA: REQUEST_ALL_DATA = 'REQUEST_ALL_DATA';

export {
  REQUEST_DATA_1,
  REQUEST_DATA_1_FAIL,
  REQUEST_DATA_1_SUCCESS,

  REQUEST_DATA_2,
  REQUEST_DATA_2_FAIL,
  REQUEST_DATA_2_SUCCESS,

  REQUEST_ALL_DATA
};
