type SEARCH_WIKIPEDIA = 'SEARCH_WIKIPEDIA';
const SEARCH_WIKIPEDIA: SEARCH_WIKIPEDIA = 'SEARCH_WIKIPEDIA';

type RECEIVE_WIKIPEDIA = 'RECEIVE_WIKIPEDIA';
const RECEIVE_WIKIPEDIA: RECEIVE_WIKIPEDIA = 'RECEIVE_WIKIPEDIA';

export {
  SEARCH_WIKIPEDIA,
  RECEIVE_WIKIPEDIA
};
