type SEARCH_WIKIPEDIA = 'SEARCH_WIKIPEDIA';
const SEARCH_WIKIPEDIA: SEARCH_WIKIPEDIA = 'SEARCH_WIKIPEDIA';

type RECEIVE_WIKIPEDIA = 'RECEIVE_WIKIPEDIA';
const RECEIVE_WIKIPEDIA: RECEIVE_WIKIPEDIA = 'RECEIVE_WIKIPEDIA';

type CLEAR_WIKIPEDIA = 'CLEAR_WIKIPEDIA';
const CLEAR_WIKIPEDIA: CLEAR_WIKIPEDIA = 'CLEAR_WIKIPEDIA';

export {
  SEARCH_WIKIPEDIA,
  RECEIVE_WIKIPEDIA,
  CLEAR_WIKIPEDIA
};
