type REQUEST_ONE = 'REQUEST_ONE';
const REQUEST_ONE: REQUEST_ONE = 'REQUEST_ONE';

type REQUEST_TWO = 'REQUEST_TWO';
const REQUEST_TWO: REQUEST_TWO = 'REQUEST_TWO';

type REQUEST_TWO_FALLBACK = 'REQUEST_TWO_FALLBACK';
const REQUEST_TWO_FALLBACK: REQUEST_TWO_FALLBACK = 'REQUEST_TWO_FALLBACK';

export {
  REQUEST_ONE,
  REQUEST_TWO,
  REQUEST_TWO_FALLBACK
};
