export const REQUEST_BOOK_SUCCESS = Symbol('REQUEST_BOOK_SUCCESS');
export const REQUEST_BOOK_FAIL = Symbol('REQUEST_BOOK_FAIL');

export const REQUEST_DOUBAN_BOOK_SUCCESS = Symbol('REQUEST_DOUBAN_BOOK_SUCCESS');
export const REQUEST_DOUBAN_BOOK_FAIL = Symbol('REQUEST_DOUBAN_BOOK_FAIL');

export const MIXIN_DOUBAN_BOOK_INTO_BOOK_LIST = Symbol('MIXIN_DOUBAN_BOOK_INTO_BOOK_LIST');
